!-----------------------------------------------------!
!                                                     !
!  Simple program to calculate rms radius of exciton  !
!  from  an a3dr file generated by plotxct.x in       !
!  the BGW suite                                      !
!                                                     !
!  Kanchan Ulman, CA2DM, NUS                          !
!                                                     !
!  Please consider citing:                            !
!  K Ulman & SY Quek, Nano Lett. 2021, 21, 8888−8894  !
!                                                     !
!-----------------------------------------------------!

      program main
      implicit none
      REAL*8 :: d1 (3), d2 (3), d3 (3), Orig (3)
      REAL*8 :: V1 (3), V2 (3), V3 (3) 
      REAL*8, allocatable :: Rho(:, :, :), Rho_Zav(:, :)
      REAL*8, allocatable :: rewfc(:, :, :), imwfc(:, :, :)
      REAL*8, allocatable :: B(:, :)
      INTEGER :: Nat, Nx, Ny, Nz, ind, idx
      INTEGER :: i
      INTEGER :: ix, iy, iz
      CHARACTER(len=100) :: dummy

      REAL*8 :: ZB, ZB1, ZB2
      REAL*8 :: xh0, yh0, zh0, xe0, ye0, ze0, xeh, yeh, zeh
      REAL*8 :: xzn, yzn, zzn, zMo
      INTEGER :: i_exc, nspin
      REAL*8 :: E_exc

      REAL*8 :: Lxby2, Lyby2, Lzby2
      REAL*8 :: Rho_tot, reh2, reh2_Rho_tot, reh_rms
      !--------------------------!
      !--------------------------!
      ! z-bounds for MoS2 wfn    !
      !--------------------------!
      ! ZB1 =  9.6597168 ! bohr  !
      ! ZB2 = 34.0150838 ! bohr  !
      !--------------------------!
      ! xzn=12.03511599521522199 !  
      ! yzn=13.91039945235715622 !
      ! zzn=12.64672361232631048 !
      ! zMo=3.492408022268541348 !
      !--------------------------!      

      !--------------------------!
      ! READ a3Dr FILE           !
      !--------------------------!
       read (5,'(a100)') dummy
       idx = index(dummy, 'ie = ') + len('ie = ') 
       read(dummy(idx:idx+6),'(I6)') i_exc 

       read (5,'(a100)') dummy
       idx = index(dummy, 'e  = ') + len('e  = ')
       read (dummy(idx:idx+12),'(F12.4)') E_exc

       read (5,'(a100)') dummy
       idx = index(dummy, 'rh = ') + len('rh = ')
       read (dummy(idx:idx+42),'(3F14.6)') xh0, yh0, zh0
       ! write (6,*) xh0, yh0, zh0

       read (5,'(a100)') dummy
       idx = index(dummy, 'spin = ') + len('spin = ')
       read (dummy(idx:idx+1),'(A1)') nspin

       read (5,*) dummy
       read (5,*) dummy       

       read (5,'(a100)') dummy
       idx = index(dummy, 'a1 = ') + len('a1 = ')
       read (dummy(idx:idx+42),'(3F14.6)') (V1(i),i=1,3)
       ! write (6,*) (V1(i),i=1,3)
       read (5,'(a100)') dummy
       idx = index(dummy, 'a2 = ') + len('a2 = ')
       read (dummy(idx:idx+42),'(3F14.6)') (V2(i),i=1,3)
       ! write (6,*) (V2(i),i=1,3)
       read (5,'(a100)') dummy
       idx = index(dummy, 'a3 = ') + len('a3 = ')
       read (dummy(idx:idx+42),'(3F14.6)') (V3(i),i=1,3)
       ! write (6,*) (V3(i),i=1,3)

       read (5,*) dummy
       read (5,'(a100)') dummy
       idx = index(dummy, 'ni = ') + len('ni = ')
       read (dummy(idx:idx+24),'(3I8)') Nx, Ny, Nz
       ! write (6,*) Nx, Ny, Nz

       read (5,*) dummy
       read (5,*) dummy

       allocate (rewfc (Nx,Ny,Nz))
       allocate (imwfc (Nx,Ny,Nz))
       allocate (Rho (Nx,Ny,Nz))

       DO iz=1,Nz
       DO iy=1,Ny
       DO ix=1,Nx
        read (5,'(3(1X,E12.5))') rewfc(ix,iy,iz), imwfc(ix,iy,iz), Rho(ix,iy,iz)
       ENDDO
       read (5,*) 
       ENDDO
       read (5,*)
       ENDDO
     !------------------------------!
     !  CALCULATE/WRITE rms radius  !
     !------------------------------!
      Lxby2=(V1(1)+V2(1)+V3(1))/2.0D0
      Lyby2=(V1(2)+V2(2)+V3(2))/2.0D0
      Lzby2=(V1(3)+V2(3)+V3(3))/2.0D0
      reh2_Rho_tot=0.0D0
      Rho_tot=0.0D0
      DO ix=1,Nx
       DO iy=1,Ny
        DO iz=1,Nz
         xe0 = (V1(1)*(ix-1)/Nx) + (V2(1)*(iy-1)/Ny) + (V3(1)*(iz-1)/Nz)
         ye0 = (V1(2)*(ix-1)/Nx) + (V2(2)*(iy-1)/Ny) + (V3(2)*(iz-1)/Nz)
         ze0 = (V1(3)*(ix-1)/Nx) + (V2(3)*(iy-1)/Ny) + (V3(3)*(iz-1)/Nz)
         !-----------------------------------------!
         ! considering contrib. on substrate only  !
         ! bound by ZB1 and ZB2                    !
         !-----------------------------------------! 
         ! if ( (ze0 .le. ZB1) .OR. (ze0 .gt. ZB2) ) then 
          xeh = (xe0 - xh0)
          yeh = (ye0 - yh0)
          zeh = (ze0 - zh0)
          !-------------------------------!
          ! Need to take care of PBC      !
          !-------------------------------!
          if ( xeh .gt. Lxby2 ) then
           xeh = xeh - (2.0D0*Lxby2)
          else if ( xeh .le. -Lxby2 ) then
           xeh = xeh + (2.0D0*Lxby2)
          endif
          !
          if ( yeh .gt. Lyby2 ) then
           yeh = yeh - (2.0D0*Lyby2)
          else if ( yeh .le. -Lyby2 ) then
           yeh = yeh + (2.0D0*Lyby2)
          endif
          !
          if ( zeh .gt. Lzby2 ) then
           zeh = zeh - (2.0D0*Lzby2)
          else if ( zeh .le. -Lzby2 ) then
           zeh = zeh + (2.0D0*Lzby2)
          endif
          !-------------------------------!
          reh2 = xeh**2 + yeh**2 + zeh**2
          reh2_Rho_tot = reh2_Rho_tot + reh2*Rho(ix,iy,iz)
          Rho_tot = Rho_tot + Rho(ix,iy,iz)
         ! endif
        ENDDO
       ENDDO
      ENDDO
      reh_rms = sqrt(reh2_Rho_tot/Rho_tot)
     !--------------------------------------------------------------!
      write (6,'(A,I6,A,F8.4,A)') " i_exc =", i_exc, & 
                ", E_exc = ", E_exc, " eV"
      write (6,'(A,F10.4,A)') " r.m.s radius = ", reh_rms, " bohr"
     !--------------------------------------------------------------!
      end program
